<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>iri</string>
		<string>src</string>
		<string>cod</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~P</string>
	<key>name</key>
	<string>iRite</string>
	<key>patterns</key>
	<array>
	<dict>

			<key>match</key>
			<string>(DisplayStatus|SetLabelText|EventChar|EventString|GetSoftwareVersion|GetUID|Time|GetEntry|
Chr|Hex|Lcase|Left|Mid|Oct|Right|Space|UCase|IntegerToString|
RealToString|SysCodeToString|GetDataRecordSize|CurrentScale|DisplayIsSuspended|EventPort|GetConsecNum|EventStatus|EventTime|Stick|
StringToReal|GetGross|GetNet|GetTare|InitDataRecording|AcquireTare|ClearTare|GetTareType|SetTare|
GetRoc|SetAccum|GetMode|GetUnits|InCoz|InMotion|InRange|SelectScale|ClearAccum|SetMode|
SetUnits|ZeroScale|GetAccum|GetAccumCount|GetAccumDate|GetAccumTime|GetAvgAccum|GetUnitsString|GetFilteredCount|GetLccd|GetLccw|GetMv|GetRawCount|GetWval|GetZeroCount|
GetCountBy|GetGrads|GetIqubeData|GetKey|KeyPress|LockKey|LockKeypad|SetConsecNum|
SetDate|SetSoftKeyText|SetSystemTime|SetTime|SetUID|UnlockKey|UnlockKeypad|
Print|SetPrintText|StartStreaming|StopStreaming|SubmitData|SubmitDSPData|
DisableSP|EnableSP|GetBatchStatus|GetCurrentSP|GetSPCaptured|GetSPBand|GetSPCount|
GetSPDuration|GetSPHyster|GetSPNSample|GetSPPReact|GetSPPreCount|GetSPTime|SetSPValue|
GetSPVOver|GetSPVUnder|PauseBatch|ResetBatch|SetBatchingMode|SetSPBand|SetSPCount|
SetSPDuration|SetSPHyster|SetSPNSample|SetSPPReact|SetSPPRecount|SetSPTime|GetSPValue|
SetSPVOver|SetSPVUnder|StartBatch|StopBatch|GetDigin|GetDigOut|SetDigOut|GetFBStatus|GetImage|GetImageReal|SetImage|SetImageReal|SetAlgOut|
ClearPulseCount|PulseCount|PulseRate|PromptUser|SelectScreen|DrawGraphic|SetBargraphLevel|SetNumericValue|SetSymbolState|SetWidgetVisibility|
GraphCreate|GraphInit|GraphPlot|GraphScale|ChartInit|ChartPlot|ChartRender|ChartInsertToExisting|ChartSetAnimation|DBAdd|DbClear|DBDelete|DBFindFirst|DBFindLast|DBFindNext|DBFindPrev|
DBGetFirst|DBGetLast|DBGetNext|DBGetPrev|DBSort|DBUpdate|ResetTimer|ResumeTimer|SetTimer|SetTimerDigOut|SetTimerMode|StartTimer|StopTimer|StringSpaceCompress|
DecodeMessage|DecodeWeight|InitHiPrec|SubmitMessage|USBFileOpen|USBFileClose|USBFileDelete|USBFileExists|ReadLn|GetUSBStatus|
SetUSBAssignment|ReleaseUSBAssignment|IsUSBDevicePresent|DBLoad|DBSave)\b</string>
			<key>name</key>
			<string>meta.variable.irite</string>
		</dict>
		<dict>
			<key>match</key>
			</dict>

		<dict>
			<key>match</key>
			<string>\b(?i:(and|array|begin|builtin|constant|database|else|elsif|end|exit|for|if|integer|is|loop|mod|not|of|or|real|record|return|step|stored|string|then|to|type|var|while))\b</string>
			<key>name</key>
			<string>keyword.control.irite</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.prototype.irite</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.prototype.irite</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:(function|procedure|handler))\b\s+(\w+(\.\w+)?)(\(.*?\))?;\s*(?=(?i:attribute|forward|external))</string>
			<key>name</key>
			<string>meta.function.prototype.irite</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.irite</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.irite</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(?i:(function|procedure|program|handler))\b\s+(\w+(\.\w+)?)</string>
			<key>name</key>
			<string>meta.function.irite</string>	
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
			<key>name</key>
			<string>constant.numeric.irite</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=--)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.irite</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>--</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.irite</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-dash.irite.one</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=//)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.irite</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>--</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.irite</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>comment.line.double-slash.irite.two</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.irite</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block.irite.one</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.irite</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>comment.block.irite.two</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.irite</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Double quoted strings are an extension and (generally) support C-style escape sequences.</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.irite</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.irite</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.irite</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.irite</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.irite</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.irite</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>''</string>
					<key>name</key>
					<string>constant.character.escape.apostrophe.irite</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.irite</string>
	<key>uuid</key>
	<string>F42FA544-6B1C-11D9-9517-000D93589AF6</string>
</dict>
</plist>
